config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'guest_login', to: 'user_sessions#guest_login'

  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['S3_BUCKET_NAME']}/sitemaps/sitemap.xml.gz")

  resources :users, only: %i[new create]
  resources :angry_cards, only: %i[new create index show destroy]
  resources :my_pages, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  post '/oauths/callback', to: 'oauth#callback'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def top; end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/top.html.erb
<div class="hero min-h-screen flex flex-col" style="background-image: url(<%= asset_path('bg_image.jpg') %>);">
  <div class="container">
    <h1 class="animate-text-shadow-pop-br text-2xl text-center mt-40 md:text-4xl font-semibold">アングリーカードジェネレーター</h1>
    <p class="w-80 mt-6 text-md py-8 ml-6 md:ml-0 md:w-full md:text-center md:animate-text-shadow-pop-br md:text-xl">俺のターン！ドロー！ストレスをアングリーカードとして召喚！<br>イラッとしたりモヤッとしたり・・日常のちょっとしたストレスを<br>カードゲーム風に遊び心を持って昇華させるためのアプリです。</p>

    <% unless logged_in? %>
    <div class="flex flex-col items-center my-6">
      <button class="btn glass rounded"><%= link_to 'ゲストログインして召喚する', guest_login_path %></button>
    </div>
    <% end %>

    
    <div class="card border bg-black rounded my-16 mx-6 md:mx-20">
      <h1 class="animate-text-shadow-pop-br text-xl md:text-3xl font-semibold my-16 text-center">遊び方</h1>
      
      <div class="hero-content flex-col lg:flex-row mb-10 mx-8">
        <div class="w-11/12 lg:w-1/3"><%= image_tag "step1.png", size:"400x260", class: "rounded shadow-2xl" %></div>
        <div class="p-4">
          <h2 class="animate-text-shadow-pop-br text-lg md:text-2xl font-semibold py-4">召喚フォームに入力しよう</h2>
          <p>イラッとしたりモヤっとした出来事を、<br>召喚フォームの「タイトル」と「内容」に入力します。</p>
          <p>入力した文章からAIがあなたのストレスの姿を画像生成し、<br>オリジナルのアングリーカードを召喚します。</p>
        </div>
      </div>

      <div class="hero-content flex-col lg:flex-row-reverse mx-8 mb-10">
        <div class="w-3/4 lg:w-1/3"><%= image_tag "step2.jpg", size:"230x200", class: "rounded shadow-2xl" %></div>
        <div class="p-4">
          <h2 class="animate-text-shadow-pop-br text-lg md:text-2xl font-semibold py-4">アングリーカード召喚！</h2>
          <p>あなたのストレスはどんなアングリーカードになって現れるでしょうか。</p>
          <p>召喚されたカードを見てクスッと気持ちが晴れるかもしれないし、<br>共有してネタとして昇華することもできます。</p>
        </div>
      </div>

      <div class="hero-content flex-col lg:flex-row mx-8 mb-14">
        <div class="w-11/12 lg:w-1/3"><%= image_tag "step3.jpg", size:"400x260", class: "rounded shadow-2xl" %></div>
        <div class="p-4">
          <h2 class="animate-text-shadow-pop-br text-lg md:text-2xl font-semibold py-4">怒りの墓場では</h2>
          <p>他のユーザーが召喚したカードを見ることができます。</p>
          <p>墓地に送られた他ユーザーのアングリーカードに共感したり、<br>自分のストレスを客観視して気持ちが昇華できるかも・・？</p>
        </div>
      </div>
     
      <% unless logged_in? %>
      <div class="flex flex-col items-center">
        <button class="btn bg-rose-900 rounded mb-12"><%= link_to 'ユーザー登録して召喚する', new_user_path %></button>
      </div>
      <% end %>
    </div>
  </div>
</div>