config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'guest_login', to: 'user_sessions#guest_login'

  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['S3_BUCKET_NAME']}/sitemaps/sitemap.xml.gz")

  resources :users, only: %i[new create]
  resources :angry_cards, only: %i[new create index show destroy]
  resources :my_pages, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  post '/oauths/callback', to: 'oauth#callback'
end

app/views/shared/_before_login_header.html.erb
<header class="navbar z-50 fixed top-0 left-0 right-0 bg-black h-20 opacity-80 flex justify-between">
  <div class="navber-start">
    <div class="dropdown visible md:hidden">
      <label tabindex="0" class="btn btn-ghost btn-circle">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
      </label>
      <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-56 text-base-content">
        <li><%= link_to '怒りの墓場', angry_cards_path, class: "btn btn-ghost lx:px-10" %></li>
        <li><%= link_to (t 'defaults.login'), login_path, class: "btn btn-ghost lx:px-10" %></li>
        <li><%= link_to (t 'defaults.register'), new_user_path, class: "btn rounded px-7 bg-rose-900" %></li>
      </ul>
    </div>

    <div class="hidden md:inline-block grid justify-items-center mb-1">
      <%= link_to root_path do %>
      <%= image_tag 'logo3.png', width: 235 %>
      <% end %>
    </div>
  </div>

  <div class="navbar-center">
    <div class="visible md:hidden">
      <%= link_to root_path do %>
        <%= image_tag 'logo3.png', width: 235, class: "ml-8" %>
      <% end %>
    </div>
  </div>

  <div class="navbar-end">
    <div class="hidden md:inline-block">
      <ul class="flex justify-end">
        <li><%= link_to '怒りの墓場', angry_cards_path, class: "btn btn-ghost text-lg lx:px-10" %></li>
        <li><%= link_to (t 'defaults.login'), login_path, class: "btn btn-ghost text-lg mr-3 lx:px-10" %></li>
        <li><%= link_to (t 'defaults.register'), new_user_path, class: "btn rounded mr-8 px-7 bg-rose-900" %></li>
      </ul>
    </div>      
  </div>
  
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error shadow-lg">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<%end%>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% case message_type %>
  <% when 'success'%>
    <div class="alert alert-success shadow-lg mt-24 mx-4 w-auto">
  <% when 'warning'%>
    <div class="alert alert-warning shadow-lg mt-24 mx-4 w-auto">
  <% when 'error' %>
    <div class="alert alert-error shadow-lg mt-24 mx-4 w-auto">
  <% else  %>
    <div class="alert alert-info shadow-lg mt-24 mx-4 w-auto">
  <% end %>
      <div>
        <%= message %>
      </div>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="bg-black">
  <footer class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <div class="flex flex-col items-center border-t pt-6">
    <nav class="flex flex-wrap justify-center md:justify-start gap-x-4 gap-y-2 md:gap-6 mb-1 text-sm">
      <%= link_to '利用規約', page_path('terms'), class: "link link-hover" %>
      <%= link_to 'プライバシーポリシー', page_path('privacy'), class: "link link-hover" %>
      <%= link_to 'お問い合わせ', 'https://forms.gle/E6hdtYZkpq5kxE3o6', class: "link link-hover" %>
    </nav>
    </div>
    <div class="text-gray-400 text-xs text-center py-3">
      Copyright ©︎ 2023 - All right reserved by Miki Ito
    </div>
  </footer>
</div>

    

app/views/shared/_header.html.erb
<header class="navbar z-50 fixed top-0 left-0 right-0 bg-black h-20 opacity-80 flex justify-between">
  <div class="navber-start">
    <div class="dropdown visible md:hidden">
      <label tabindex="0" class="btn btn-ghost btn-circle">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
      </label>
      <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-56 text-base-content">
        <li><%= link_to '怒りの墓場', angry_cards_path, class: "btn btn-ghost lx:px-10" %></li>
        <li><%= link_to '召喚する', new_angry_card_path, class: "btn btn-ghost lx:px-10" %></li>
      </ul>
    </div>

    <div class="hidden md:inline-block grid justify-items-center mb-1">
      <%= link_to root_path do %>
      <%= image_tag 'logo3.png', width: 235 %>
      <% end %>
    </div>
  </div>

  <div class="navbar-center">
    <div class="visible md:hidden">
      <%= link_to root_path do %>
        <%= image_tag 'logo3.png', width: 235, class: "ml-4" %>
      <% end %>
    </div>
  </div>

  <div class="navbar-end">
    <div class="hidden md:inline-block">
      <ul class="flex justify-end">
        <li><%= link_to '怒りの墓場', angry_cards_path, class: "btn btn-ghost text-lg lx:px-10" %></li>
        <li><%= link_to '召喚する', new_angry_card_path, class: "btn btn-ghost text-lg mr-3 lx:px-10" %></li>
      </ul>
    </div>
    <div class="dropdown dropdown-end mt-2 mr-6">
      <label tabindex="0" class="btn btn-ghost btn-circle avatar">
        <div class="w-20 rounded-full">
          <% if current_user.avatar_url %>
            <%= image_tag current_user.avatar_url, size: "400x400" %>
          <% else %>
            <%= image_tag('user_sample.png', size: "400x400") %>
          <% end %>
        </div>
      </label>

      <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52 text-base-content">
        <li><%= link_to 'マイページ', my_page_path(current_user.id) %></li>
        <li><%= link_to (t 'defaults.logout'), logout_path, method: :delete %></li>
      </ul>
    </div>
    
  </div>
  
</header>