config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'guest_login', to: 'user_sessions#guest_login'

  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['S3_BUCKET_NAME']}/sitemaps/sitemap.xml.gz")

  resources :users, only: %i[new create]
  resources :angry_cards, only: %i[new create index show destroy]
  resources :my_pages, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  post '/oauths/callback', to: 'oauth#callback'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new; end
  
  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end
  
  def destroy
    logout
    #flash[:success] = t('.success')
    redirect_to root_path, success: t('.success')
  end

  def guest_login
    redirect_to root_path, alert: 'すでにログインしています' if current_user

    random_value = SecureRandom.hex
    guest = User.create!(name: 'ゲスト', email: "guest_#{random_value}@example.com", password: "#{random_value}", password_confirmation: "#{random_value}", guest: true)
    auto_login(guest)
    redirect_to new_angry_card_path, success: 'ゲストユーザーとしてログインしました'
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div class="hero min-h-screen bg-cover" style="background-image: url(<%= asset_path('bg_image.jpg') %>);">
  <div class="hero-content flex-col border rounded bg-black mt-14 opacity-90">
    <div class="text-center mt-6">
      <h1 class="text-2xl md:text-3xl font-semibold py-3"><%= t '.title' %></h1>
    </div>
    <div class="card w-full md:w-96 shadow-2xl">
      <div class="card-body">
        <%= form_with url: login_path, local: true do |f| %>
          <div class="form-control">
            <%= f.label :email, User.human_attribute_name(:email)%>
            <%= f.text_field :email, class: 'input input-bordered text-gray-800 rounded bg-gray-300 mb-3 mt-1' %>
          </div>
          <div class="form-control my-2">
            <%= f.label :password, User.human_attribute_name(:password) %>
            <%= f.password_field :password, class: 'input input-bordered text-gray-800 rounded text-gray-800 bg-gray-300 mb-3 mt-1' %>
          </div>
          <div class="form-control my-4 pt-4">
            <%= f.submit (t 'defaults.login'), class: 'btn btn-primary rounded' %>
          </div>
          <div class="text-center mb-2">
            <p>パスワードをお忘れの方は<%= link_to "こちら", new_password_reset_path, class: "link" %></p>
          </div>
          <div class="text-center mp-6">--------------------or--------------------</div>
          <div class="mt-3">
            <!-- クライアントライブラリの読み込み 下記1行を追加 -->
            <script src="https://accounts.google.com/gsi/client" async defer></script>
            <!-- Googleログインボタンの表示 ここから追加 -->
            <div id="g_id_onload"
              data-client_id= <%= ENV['GOOGLE_CLIENT_ID'] %>
              data-login_uri="https://www.angrycard-generator.com/oauths/callback"
              data-auto_prompt="false">
            </div>
            <div class="g_id_signin flex justify-center bg-black"
              data-type="standard"
              data-size="large"
              data-theme="outline"
              data-text="sign_in_with"
              data-shape="rectangular"
              data-logo_alignment="left">
            </div>
            <!-- ここまで追加 -->
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>